# Generated by Django 5.2.7 on 2025-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLogoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('logout_type', models.CharField(choices=[('self', 'Self Logout'), ('global', 'Global Logout'), ('admin', 'Admin Force Logout')], default='global', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('sessions_affected', models.PositiveIntegerField(default=0)),
                ('completed_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'keycloak_global_logout_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('logout_requested', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'keycloak_user_sessions',
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='keycloak_us_user_id_d0d7f0_idx'), models.Index(fields=['username', 'is_active'], name='keycloak_us_usernam_6ae83b_idx'), models.Index(fields=['expires_at'], name='keycloak_us_expires_7e1614_idx')],
            },
        ),
    ]
